CREATE WAREHOUSE IF NOT EXISTS ECOMMERCE_WH_2305349
WITH
    WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND = 120
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE;

    CREATE DATABASE IF NOT EXISTS ECOMMERCE_2305349;

    USE DATABASE ECOMMERCE_2305349;

CREATE SCHEMA IF NOT EXISTS BRONZE;
CREATE SCHEMA IF NOT EXISTS SILVER;
CREATE SCHEMA IF NOT EXISTS GOLD;

USE WAREHOUSE ECOMMERCE_WH_2305349;

USE DATABASE ECOMMERCE_2305349;
USE SCHEMA GOLD;

SELECT CURRENT_WAREHOUSE() AS warehouse,
       CURRENT_DATABASE() AS database,
       CURRENT_SCHEMA() AS schema;

       USE DATABASE ECOMMERCE_2305349;
USE SCHEMA GOLD;

SHOW TABLES;

SELECT * FROM ECOMMERCE_2305349.GOLD.EXECUTIVE_KPIS;

SELECT
    'MONTHLY_DELIVERY' AS TABLE_NAME,
    COUNT(*) AS ROW_COUNT
FROM ECOMMERCE_2305349.GOLD.MONTHLY_DELIVERY

UNION ALL

SELECT
    'SELLER_PERFORMANCE',
    COUNT(*)
FROM ECOMMERCE_2305349.GOLD.SELLER_PERFORMANCE

UNION ALL

SELECT
    'CATEGORY_PERFORMANCE',
    COUNT(*)
FROM ECOMMERCE_2305349.GOLD.CATEGORY_PERFORMANCE

UNION ALL

SELECT
    'CANCELLATION_INTELLIGENCE',
    COUNT(*)
FROM ECOMMERCE_2305349.GOLD.CANCELLATION_INTELLIGENCE;